name: financial_management
description: Financial management by ngthminhdev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  material_symbols_icons: ^4.2719.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  formz: ^0.7.0
  equatable: ^2.0.5
  page_transition: ^2.1.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.4.56
  syncfusion_flutter_core: ^19.4.56
  auto_size_text: ^3.0.0
  remixicon: ^1.2.0
  flutter_randomcolor: ^1.0.14
  animations: ^2.0.8
  flutter_animate: ^4.5.0
  flutter_masked_text2: ^0.9.1
  flutter_launcher_icons: ^0.13.1
  ionicons: ^0.2.2
  syncfusion_flutter_datepicker: ^19.4.56
  animated_text_kit: ^4.2.2
  syncfusion_localizations: ^19.4.56
  introduction_screen: ^3.1.12
  dots_indicator: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  http: ^1.1.0
  loading_animation_widget: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  syncfusion_flutter_core: 19.4.56

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_2.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
